
// swiftlint:disable type_body_length
public enum CDYelpCategoryAlias: String {
    // Food
    case food                       = "food"
    case acaiBowls                  = "acaibowls"
    case backshop                   = "backshop"
    case bagels                     = "bagels"
    case bakeries                   = "bakeries"
    case beerWineAndSpirits         = "beer_and_wine"
    case bento                      = "bento"
    case beverageStore              = "beverage_stores"
    case breweries                  = "breweries"
    case bubbleTea                  = "bubbletea"
    case butcher                    = "butcher"
    case beef                       = "Beef"
    case csa                        = "csa"
    case chimneyCakes               = "chimneycakes"
    case churros                    = "churros"
    case cideries                   = "cideries"
    case coffeeAndTea               = "coffee"
    case coffeeAndTeaSupplies       = "coffeeteasupplies"
    case coffeeRoasteries           = "coffeeroasteries"
    case convenienceStores          = "convenience"
    case cupcakes                   = "cupcakes"
    case customCakes                = "customcakes"
    case delicatessen               = "delicatessen"
    case desserts                   = "desserts"
    case distilleries               = "distilleries"
    case doItYourselfFood           = "diyfood"
    case donairs                    = "donairs"
    case donuts                     = "donuts"
    case empanadas                  = "empanadas"
    case ethicGrocery               = "ethicgrocery"
    case fish                       = "fish"
    case seaFood                    = "seaFood"
    case farmersMarket              = "farmersmarket"
    case fishmonger                 = "fishmonger"
    case foodDeliveryServices       = "fooddeliveryservices"
    case foodTrucks                 = "foodtrucks"
    case friterie                   = "friterie"
    case gelato                     = "gelato"
    case grocery                    = "grocery"
    case hawkerCentre               = "hawkercentre"
    case honey                      = "honey"
    case iceCreamAndFrozenYogurt    = "icecream"
    case importedFood               = "importedfood"
    case internationalGrocery       = "intlgrocery"
    case internetCafes              = "internetcafe"
    case japaneseSweets             = "jpsweets"
    case taiyaki                    = "taiyaki"
    case juiceBarsAndSmoothies      = "juicebars"
    case kombucha                   = "kombucha"
    case milkshakeBars              = "milkshakebars"
    case mulledWine                 = "gluhwein"
    case nasiLemak                  = "nasilemak"
    case organicStores              = "organic_stores"
    case panzerotti                 = "panzerotti"
    case patisserieAndCakeShop      = "cakeshop"
    case piadina                    = "piadina"
    case poke                       = "poke"
    case pretzels                   = "pretzels"
    case salumerie                  = "salumerie"
    case shavedIce                  = "shavedice"
    case shavedSnow                 = "shavedsnow"
    case smokehouse                 = "smokehouse"
    case specialtyFood              = "gourmet"
    case candyStores                = "candy"
    case cheeseShops                = "cheese"
    case chocolatiersAndShops       = "chocolate"
    case dagashi                    = "dagashi"
    case driedFruit                 = "driedfruit"
    case frozenFood                 = "frozenfood"
    case fruitsAndVeggies           = "markets"
    case healthMarkets              = "healthmarkets"
    case herbsAndSpices             = "herbsandspices"
    case macarons                   = "macarons"
    case meatShops                  = "meats"
    case oliveOil                   = "oliveoil"
    case pastaShops                 = "pastashops"
    case popcornShops               = "popcorn"
    case seafoodMarkets             = "seafoodmarkets"
    case tofuShops                  = "tofu"
    case streetVendors              = "streetvendors"
    case sugarShacks                = "sugarshacks"
    case teaRooms                   = "tea"
    case torshi                     = "torshi"
    case tortillas                  = "tortillas"
    case waterStores                = "waterstores"
    case wineries                   = "wineries"
    case zapiekanka                 = "zapiekanka"

   // Restaurants
    case restaurants                = "restaurants"
    case afghan                     = "afghani"
    case african                    = "african"
    case senegalese                 = "senegalese"
    case southAfrican               = "southafrican"
    case newAmerican                = "newamerican"
    case traditionalAmerican        = "tradamerican"
    case andalusian                 = "andalusian"
    case arabian                    = "arabian"
    case arabPizza                  = "arabpizza"
    case argentine                  = "argentine"
    case armenian                   = "armenian"
    case asianFusion                = "asianfusion"
    case asturian                   = "asturian"
    case australian                 = "australian"
    case austrian                   = "austrian"
    case baguettes                  = "baguettes"
    case bangladeshi                = "bangladeshi"
    case barbeque                   = "bbq"
    case basque                     = "basque"
    case bavarian                   = "bavarian"
    case beerGarden                 = "beergarden"
    case beerHall                   = "beerhall"
    case beisl                      = "beisl"
    case belgian                    = "belgian"
    case flemish                    = "flemish"
    case bistros                    = "bistros"
    case blackSea                   = "blacksea"
    case brasseries                 = "brasseries"
    case brazilian                  = "brazilian"
    case brazilianEmpanadas         = "brazilianempanadas"
    case centralBrazilian           = "centralbrazilian"
    case northeasternBrazilian      = "northeasternbrazilian"
    case northernBrazilian          = "northernbrazilian"
    case rodizios                   = "rodizios"
    case breakfastAndBrunch         = "breakfast_brunch"
    case british                    = "british"
    case buffets                    = "buffets"
    case bulgarian                  = "bulgarian"
    case burgers                    = "burgers"
    case burmese                    = "burmese"
    case cafes                      = "cafes"
    case themedCafes                = "themedcafes"
    case cafeteria                  = "cafeteria"
    case cajunAndCreole             = "cajun"
    case cambodian                  = "cambodian"
    case newCanadian                = "newcanadian"
    case canteen                    = "canteen"
    case caribbean                  = "caribbean"
    case dominican                  = "dominican"
    case haitian                    = "haitian"
    case puertoRican                = "puertorican"
    case trinidadian                = "trinidadian"
    case catalan                    = "catalan"
    case cheesesteaks               = "cheesesteaks"
    case chickenShop                = "chickenshop"
    case chickenWings               = "chicken_wings"
    case chilean                    = "chilean"
    case chinese                    = "chinese"
    case cantonese                  = "cantonese"
    case congee                     = "congee"
    case dimSum                     = "dimsum"
    case fuzhou                     = "fuzhou"
    case hainan                     = "hainan"
    case hakka                      = "hakka"
    case henghwa                    = "henghwa"
    case hokkien                    = "hokkien"
    case hunan                      = "hunan"
    case pekinese                   = "pekinese"
    case shanghainese               = "shanghainese"
    case szechuan                   = "szechuan"
    case teochew                    = "teochew"
    case comfortFood                = "comfort_food"
    case corsican                   = "corsican"
    case creperies                  = "creperies"
    case cuban                      = "cuban"
    case currySausage               = "currysausage"
    case cypriot                    = "cypriot"
    case czech                      = "czech"
    case czechAndSlovakian          = "czechslovakian"
    case danish                     = "danish"
    case delis                      = "delis"
    case diners                     = "diners"
    case dinnerTheater              = "dinnertheater"
    case dumplings                  = "dumplings"
    case easternEuropean            = "eastern_european"
    case ethiopian                  = "ethiopian"
    case fastFood                   = "hotdogs"
    case filipino                   = "filipino"
    case fischbroetchen             = "fischbroetchen"
    case fishAndChips               = "fishnchips"
    case flatbread                  = "flatbread"
    case fondue                     = "fondue"
    case foodCourt                  = "food_court"
    case foodStands                 = "foodstands"
    case freiduria                  = "freiduria"
    case french                     = "french"
    case alsatian                   = "alsatian"
    case auvergnat                  = "auvergnat"
    case berrichon                  = "berrichon"
    case bourguignon                = "bourguignon"
    case mauritius                  = "mauritius"
    case nicoise                    = "nicois"
    case provencal                  = "provencal"
    case reunion                    = "reunion"
    case frenchSouthwest            = "sud_ouest"
    case galician                   = "galician"
    case gameMeat                   = "gamemeat"
    case gastropubs                 = "gastropubs"
    case georgian                   = "georgian"
    case german                     = "german"
    case baden                      = "baden"
    case easternGerman              = "easterngerman"
    case franconian                 = "franconian"
    case hessian                    = "hessian"
    case northernGerman             = "northerngerman"
    case palatine                   = "palatine"
    case rhinelandian               = "rhinelandian"
    case giblets                    = "giblets"
    case glutenFree                 = "gluten_free"
    case greek                      = "greek"
    case guamanian                  = "guamanian"
    case halal                      = "halal"
    case hawaiian                   = "hawaiian"
    case heuriger                   = "heuriger"
    case himalayanAndNepalese       = "himalayan"
    case honduran                   = "honduran"
    case hongKongStyleCafe          = "hkcafe"
    case hotDogs                    = "hotdog"
    case hotPot                     = "hotpot"
    case hungarian                  = "hungarian"
    case iberian                    = "iberian"
    case indian                     = "indpak"
    case indonesian                 = "indonesian"
    case international              = "international"
    case irish                      = "irish"
    case islandPub                  = "island_pub"
    case israeli                    = "israeli"
    case italian                    = "italian"
    case abruzzese                  = "abruzzese"
    case altoatesine                = "altoatesine"
    case apulian                    = "apulian"
    case calabrian                  = "calabrian"
    case cucinaCampana              = "cucinacampana"
    case emilian                    = "emilian"
    case friulan                    = "friulan"
    case ligurian                   = "ligurian"
    case lumbard                    = "lumbard"
    case napoletana                 = "napoletana"
    case piemonte                   = "piemonte"
    case roman                      = "roman"
    case sardinian                  = "sardinian"
    case sicilian                   = "sicilian"
    case tuscan                     = "tuscan"
    case venetian                   = "venetian"
    case japanese                   = "japanese"
    case blowfish                   = "blowfish"
    case conveyorBeltSushi          = "conveyorsushi"
    case donburi                    = "donburi"
    case gyudon                     = "gyudon"
    case oyakodon                   = "oyakodon"
    case handRolls                  = "handrolls"
    case horumon                    = "horumon"
    case izakaya                    = "izakaya"
    case japaneseCurry              = "japacurry"
    case kaiseki                    = "kaiseki"
    case kushikatsu                 = "kushikatsu"
    case oden                       = "oden"
    case okinawan                   = "okinawan"
    case okonomiyaki                = "okonomiyaki"
    case onigiri                    = "onigiri"
    case ramen                      = "ramen"
    case robatayaki                 = "robatayaki"
    case soba                       = "soba"
    case sukiyaki                   = "sukiyaki"
    case takoyaki                   = "takoyaki"
    case tempura                    = "tempura"
    case teppanyaki                 = "teppanyaki"
    case tonkatsu                   = "tonkatsu"
    case udon                       = "udon"
    case unagi                      = "unagi"
    case westernStyleJapaneseFood   = "westernjapanese"
    case yakiniku                   = "yakiniku"
    case yakitori                   = "yakitori"
    case jewish                     = "jewish"
    case kebab                      = "kebab"
    case kopitiam                   = "kopitiam"
    case korean                     = "korean"
    case kosher                     = "kosher"
    case kurdish                    = "kurdish"
    case laos                       = "laos"
    case laotian                    = "laotian"
    case latinAmerican              = "latin"
    case colombian                  = "colombian"
    case salvadoran                 = "salvadoran"
    case venezuelan                 = "venezuelan"
    case liveAndRawFood             = "raw_food"
    case lyonnais                   = "lyonnais"
    case malaysian                  = "malaysian"
    case mamak                      = "mamak"
    case nyonya                     = "nyonya"
    case meatballs                  = "meatballs"
    case mediterranean              = "mediterranean"
    case falafel                    = "falafel"
    case mexican                    = "mexican"
    case easternMexican             = "easternmexican"
    case jaliscan                   = "jaliscan"
    case northernMexican            = "northernmexican"
    case oaxacan                    = "oaxacan"
    case pueblan                    = "pueblan"
    case tacos                      = "tacos"
    case tamales                    = "tamales"
    case yucatan                    = "yucatan"
    case middleEastern              = "mideastern"
    case egyptian                   = "egyptian"
    case lebanese                   = "lebanese"
    case milkBars                   = "milkbars"
    case modernAustralian           = "modern_australian"
    case modernEuropean             = "modern_european"
    case mongolian                  = "mongolian"
    case moroccan                   = "moroccan"
    case newMexicanCuisine          = "newmexican"
    case newZealand                 = "newzealand"
    case nicaraguan                 = "nicaraguan"
    case nigerian                   = "nigerian"
    case nightFood                  = "nightfood"
    case nikkei                     = "nikkei"
    case noodles                    = "noodles"
    case norcinerie                 = "norcinerie"
    case openSandwiches             = "opensandwiches"
    case oriental                   = "oriental"
    case pfAndComercial             = "pfcomercial"
    case pakistani                  = "pakistani"
    case panAsian                   = "panasian"
    case parentCafes                = "eltern_cafes"
    case parma                      = "parma"
    case persianAndIranian          = "persian"
    case peruvian                   = "peruvian"
    case pita                       = "pita"
    case pizza                      = "pizza"
    case polish                     = "polish"
    case pierogis                   = "pierogis"
    case popUpRestaurants           = "popuprestaurants"
    case portuguese                 = "portuguese"
    case alentejo                   = "alentejo"
    case algarve                    = "algarve"
    case azores                     = "azores"
    case beira                      = "beira"
    case fadoHouses                 = "fado_houses"
    case madeira                    = "madeira"
    case minho                      = "minho"
    case ribatejo                   = "ribatejo"
    case trasOsMontes               = "tras_os_montes"
    case potatoes                   = "potatoes"
    case poutineries                = "poutineries"
    case pubFood                    = "pubfood"
    case rice                       = "riceshop"
    case romanian                   = "romanian"
    case rotisserieChicken          = "rotisserie_chicken"
    case russian                    = "russian"
    case salad                      = "salad"
    case sandwiches                 = "sandwiches"
    case scandinavian               = "scandinavian"
    case schnitzel                  = "schnitzel"
    case scottish                   = "scottish"
    case seafood                    = "seafood"
    case serboCroatian              = "serbocroatian"
    case signatureCuisine           = "signature_cuisine"
    case singaporean                = "singaporean"
    case slovakian                  = "slovakian"
    case soulFood                   = "soulfood"
    case soup                       = "soup"
    case southern                   = "southern"
    case spanish                    = "spanish"
    case arroceriaAndPaella         = "arroceria_paella"
    case sriLankan                  = "srilankan"
    case steakhouses                = "steak"
    case supperClubs                = "supperclubs"
    case sushiBars                  = "sushi"
    case swabian                    = "swabian"
    case swedish                    = "swedish"
    case swissFood                  = "swissfood"
    case syrian                     = "syrian"
    case tabernas                   = "tabernas"
    case taiwanese                  = "taiwanese"
    case tapasBars                  = "tapas"
    case tapasAndSmallPlates        = "tapasmallplates"
    case tavolaCalda                = "tavolacalda"
    case texMex                     = "tex-mex"
    case thai                       = "thai"
    case traditionalNorwegian       = "norwegian"
    case traditionalSwedish         = "traditional_swedish"
    case trattorie                  = "trattorie"
    case turkish                    = "turkish"
    case cheeKufta                  = "cheekufta"
    case gozleme                    = "gozleme"
    case homemadeFood               = "homemadefood"
    case lahmacun                   = "lahmacun"
    case ottomanCuisine             = "ottomancuisine"
    case turkishRavioli             = "turkishravioli"
    case ukrainian                  = "ukrainian"
    case uzbek                      = "uzbek"
    case vegan                      = "vegan"
    case vegetarian                 = "vegetarian"
    case venison                    = "venison"
    case vietnamese                 = "vietnamese"
    case waffles                    = "waffles"
    case wok                        = "wok"
    case wraps                      = "wraps"
    case yugoslav                   = "yugoslav"
    
    static let yelpCategory:[CDYelpCategoryAlias] = [.abruzzese, .acaiBowls, .african, .asianFusion, .bagels, .bakeries, .barbeque, .beef, .bistros, .brazilian, .bubbleTea, .brasseries, .breakfastAndBrunch, .bento, .breweries, .buffets, .burgers, .cafeteria, .caribbean, .cheesesteaks, .chickenShop, .chickenWings, .chinese, .coffeeAndTea, .colombian, .comfortFood, .creperies, .cuban, .cupcakes, .danish, .desserts, .diners, .dominican, .donuts, .dumplings, .empanadas, .falafel, .fastFood, .fish, .fishAndChips, .foodTrucks, .french, .gelato, .german, .glutenFree, .greek, .haitian, .hawaiian, .halal, .homemadeFood, .hotPot, .hotDogs, .iceCreamAndFrozenYogurt, .indian, .irish, .italian, .japanese, .jewish, .kebab, .korean, .kosher, .mexican, .nigerian, .noodles, .pakistani, .pita, .pizza, .rice, .seaFood, .sandwiches, .sushiBars, .spanish, .soup, .soulFood, .steakhouses, .streetVendors, .thai, .vegan, .vegetarian, .wraps, .waffles]
}

//A list of the business attributes the Yelp Fusion API supports.

public enum CDYelpAttributeFilter: String {
    case hotAndNew              = "hot_and_new"
    case requestAQuote          = "request_a_quote"
    case reservation            = "reservation"
    case waitlistReservation    = "waitlist_reservation"
    case cashback               = "cashback"
    case deals                  = "deals"
    case genderNeutralRestrooms = "gender_neutral_restrooms"
    case openToAll              = "open_to_all"
    case wheelchairAccessible   = "wheelchair_accessible"
}

/// A list of the event sortOn types the Yelp Fusion API supports.
///
public enum CDYelpEventSortOnType: String {
    case popularity = "popularity"
    case timeStart  = "time_start"
}


public enum CDYelpBusinessMatchThresholdType: String {
    //Do not apply any match quality threshold; all potential business matches will be returned.
    case none
    // Apply a match quality threshold such that only very closely matching businesses will be returned.
    case normal = "default"
    // Apply a very strict match quality threshold.
    case strict
}

// A list of the business sort types the Yelp Fusion API supports.

public enum CDYelpBusinessSortType: String {
    case bestMatch      = "best_match"
    case rating         = "rating"
    case reviewCount    = "review_count"
    case distance       = "distance"
}

public enum CDYelpEventSortByType: String {
    case ascending  = "asc"
    case descending = "desc"
}

// A list of locales the Yelp Fusion API supports. The locale code is in the format of {language code}_{country code}.

public enum CDYelpLocale: String {
    case chinese_hongKong           = "zh_HK"
    case chinese_taiwan             = "zh_TW"
    case czech_czechRepublic        = "cs_CZ"
    case danish_denmark             = "da_DK"
    case dutch_belgium              = "nl_BE"
    case dutch_theNetherlands       = "nl_NL"
    case english_australia          = "en_AU"
    case english_belgium            = "en_BE"
    case english_canada             = "en_CA"
    case english_hongKong           = "en_HK"
    case english_malaysia           = "en_MY"
    case english_newZealand         = "en_NZ"
    case english_philippines        = "en_PH"
    case english_republicOfIreland  = "en_IE"
    case english_singapore          = "en_SG"
    case english_switzerland        = "en_CH"
    case english_unitedKingdom      = "en_GB"
    case english_unitedStates       = "en_US"
    case filipino_philippines       = "fil_PH"
    case finnish_finland            = "fi_FI"
    case french_belgium             = "fr_BE"
    case french_canada              = "fr_CA"
    case french_france              = "fr_FR"
    case french_switzerland         = "fr_CH"
    case german_austria             = "de_AT"
    case german_germany             = "de_DE"
    case german_switzerland         = "de_CH"
    case italian_italy              = "it_IT"
    case italian_switzerland        = "it_CH"
    case japanese_japan             = "ja_JP"
    case malay_malaysia             = "ms_MY"
    case norwegian_norway           = "nb_NO"
    case polish_poland              = "pl_PL"
    case portuguese_brazil          = "pt_BR"
    case portuguese_portugal        = "pt_PT"
    case spanish_argentina          = "es_AR"
    case spanish_chile              = "es_CL"
    case spanish_mexico             = "es_MX"
    case spanish_spain              = "es_ES"
    case swedish_finland            = "sv_FI"
    case swedish_sweden             = "sv_SE"
    case turkish_turkey             = "tr_TR"
}

// A list of the price tiers the Yelp Fusion API supports.

public enum CDYelpPriceTier: String {
    case oneDollarSign      = "1"
    case twoDollarSigns     = "2"
    case threeDollarSigns   = "3"
    case fourDollarSigns    = "4"
}


// A list of the number of filled stars the Yelp stars asset can be returned with.

public enum CDYelpStars: String {
    case zero       = "zero"
    case one        = "one"
    case oneHalf    = "one_half"
    case two        = "two"
    case twoHalf    = "two_half"
    case three      = "three"
    case threeHalf  = "three_half"
    case four       = "four"
    case fourHalf   = "four_half"
    case five       = "five"
}


// A list of the sizes the Yelp stars asset can be returned in.

public enum CDYelpStarsSize: String {
    case small      = "small"
    case regular    = "regular"
    case large      = "large"
    case extraLarge = "extra_large"
}

// A list of the transaction types the Yelp Fusion API supports. Currently, only food delivery is supported and it is only supported in the U.S.

public enum CDYelpTransactionType: String {
    case foodDelivery           = "delivery"
    case pickup                 = "pickup"
    case restaurantReservation  = "restaurant_reservation"
}

